import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="md:flex justify-between  mb-3 border-b-2 border-gray-200">
          <h2 className=" text-[#A59DFF] text-lg md:text-xs">1.0</h2>
          <h2 className="text-[#A59DFF] text-lg md:text-xs">Наши услуги</h2>
          <div></div>
        </div>
        {children}
      </body>
    </html>
  );
}
